{% set name = "python-keystoneclient" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d93efd494b43d8b4cd8a62281c82d3f02aa531c5523e6bbe7d696e37bc77ba8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python >=3.6
    - setuptools
  run:
    - debtcollector
    - keystoneauth1
    - oslo.config
    - oslo.i18n
    - oslo.serialization
    - oslo.utils
    - pbr
    - python >=3.6
    - requests
    - setuptools
    - six
    - stevedore

test:
  imports:
    - keystoneclient

about:
  home: https://github.com/openstack/python-keystoneclient
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Client Library for OpenStack Identity
  doc_url: https://docs.openstack.org/python-keystoneclient/latest/
  dev_url: https://opendev.org/openstack/python-keystoneclient

extra:
  recipe-maintainers:
    - tschoonj
